/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ccsd.vernier;

public class ExperimentConfig implements 
	org.concord.sensor.ExperimentConfig
 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ExperimentConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExperimentConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      NativeBridgeJNI.delete_ExperimentConfig(swigCPtr);
    }
    swigCPtr = 0;
  }

	public boolean isValid()
	{
		return getValid() == 1;
	}
	
	public boolean getExactPeriod()
	{
		return getExactPeriodUChar() == 1;
	}
	
	public org.concord.sensor.SensorConfig [] getSensorConfigs()
	{
		int num = getNumSensorConfigs();
		SensorConfig [] configs = new SensorConfig [num];
		for(int i=0; i<num; i++) {
			configs[i] = getSensorConfig(i);
		}
		
		return configs;
	}

  public void setValid(short value) {
    NativeBridgeJNI.ExperimentConfig_valid_set(swigCPtr, this, value);
  }

  public short getValid() {
    return NativeBridgeJNI.ExperimentConfig_valid_get(swigCPtr, this);
  }

  public void setInvalidReason(String value) {
    NativeBridgeJNI.ExperimentConfig_invalidReason_set(swigCPtr, this, value);
  }

  public String getInvalidReason() {
    return NativeBridgeJNI.ExperimentConfig_invalidReason_get(swigCPtr, this);
  }

  public void setPeriod(float value) {
    NativeBridgeJNI.ExperimentConfig_period_set(swigCPtr, this, value);
  }

  public float getPeriod() {
    return NativeBridgeJNI.ExperimentConfig_period_get(swigCPtr, this);
  }

  public void setExactPeriodUChar(short value) {
    NativeBridgeJNI.ExperimentConfig_exactPeriodUChar_set(swigCPtr, this, value);
  }

  public short getExactPeriodUChar() {
    return NativeBridgeJNI.ExperimentConfig_exactPeriodUChar_get(swigCPtr, this);
  }

  public void setNumberOfSamples(int value) {
    NativeBridgeJNI.ExperimentConfig_numberOfSamples_set(swigCPtr, this, value);
  }

  public int getNumberOfSamples() {
    return NativeBridgeJNI.ExperimentConfig_numberOfSamples_get(swigCPtr, this);
  }

  public void setDataReadPeriod(float value) {
    NativeBridgeJNI.ExperimentConfig_dataReadPeriod_set(swigCPtr, this, value);
  }

  public float getDataReadPeriod() {
    return NativeBridgeJNI.ExperimentConfig_dataReadPeriod_get(swigCPtr, this);
  }

  public void setDeviceName(String value) {
    NativeBridgeJNI.ExperimentConfig_deviceName_set(swigCPtr, this, value);
  }

  public String getDeviceName() {
    return NativeBridgeJNI.ExperimentConfig_deviceName_get(swigCPtr, this);
  }

  public void setNumSensorConfigs(int value) {
    NativeBridgeJNI.ExperimentConfig_numSensorConfigs_set(swigCPtr, this, value);
  }

  public int getNumSensorConfigs() {
    return NativeBridgeJNI.ExperimentConfig_numSensorConfigs_get(swigCPtr, this);
  }

  public void setSensorConfigArray(SensorConfig value) {
    NativeBridgeJNI.ExperimentConfig_sensorConfigArray_set(swigCPtr, this, SensorConfig.getCPtr(value), value);
  }

  public SensorConfig getSensorConfigArray() {
    long cPtr = NativeBridgeJNI.ExperimentConfig_sensorConfigArray_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SensorConfig(cPtr, false);
  }

  public SensorConfig getSensorConfig(int i) {
    long cPtr = NativeBridgeJNI.ExperimentConfig_getSensorConfig(swigCPtr, this, i);
    return (cPtr == 0) ? null : new SensorConfig(cPtr, false);
  }

  public void createSensorConfigArray(int size) {
    NativeBridgeJNI.ExperimentConfig_createSensorConfigArray(swigCPtr, this, size);
  }

  public void setSensorConfig(SensorConfig sConfig, int i) {
    NativeBridgeJNI.ExperimentConfig_setSensorConfig(swigCPtr, this, SensorConfig.getCPtr(sConfig), sConfig, i);
  }

  public ExperimentConfig() {
    this(NativeBridgeJNI.new_ExperimentConfig(), true);
  }

}
