/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ccsd.vernier;

public class SensorParam {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SensorParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SensorParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      NativeBridgeJNI.delete_SensorParam(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setKey(String value) {
    NativeBridgeJNI.SensorParam_key_set(swigCPtr, this, value);
  }

  public String getKey() {
    return NativeBridgeJNI.SensorParam_key_get(swigCPtr, this);
  }

  public void setValue(String value) {
    NativeBridgeJNI.SensorParam_value_set(swigCPtr, this, value);
  }

  public String getValue() {
    return NativeBridgeJNI.SensorParam_value_get(swigCPtr, this);
  }

  public SensorParam() {
    this(NativeBridgeJNI.new_SensorParam(), true);
  }

}
